.eslintrc.cjs, src/core/injector/core/launcher.js, src/core/injector/core/launcher.spec.js, src/core/injector/index.js, src/core/injector/index.spec.js, src/index.js
1. Now to make experience with multiple slots on a page at most smooth use iframe 'name' attribute to pass an id. Otherwise it will be self-assigned and raised to parent app with '$created' event - but this requires additional handling
2. To disable auto-resizing events pass a second argument (options) to a `createApp` main exported function as an object with prop `disableAutoResizing` set to `true`: `createApp({...}, { disableAutoResizing: true })`
=> Id will be now be received from <iframe name> attribute

package.json, src/core/boiler-plugins/vue-plugin.js, src/core/boiler-plugins/vue-plugin.spec.js, src/core/boiler/core/helpers.js, src/core/boiler/core/widgetFactory.js, src/core/boiler/core/widgetFactory.spec.js, webpack.config.js
This will align experience of using widgets inside plain JS apps as well as complex SPA's with own lifecycle
In fact now instead of mounting an app on a widget element directly it mounts it inside a shadow DOM zone inside it. Content that is provided from outside is now put into a slot that app navigates to a particular place where it suppose to be rendered. This means content and widget are handled separately although they are displayed one inside another.
*there is a quite raw solution for passing styles to shadow DOM sections. I hope I will come up with something more clean down the road
=> Mount widgets with Shadow DOM

package.json, webpack.config.js
This PR changes the webpack's devServer config so it exposes the built files directly on the development server url.
This means that we can import the toolkit, while running the dev server, either via `<script type="module" src="http://localhost:3003"></script>` when used directly in an html file, or via the `import` function in any js module (`import('http://localhost:3003').then(module => ... )`) or in webpack (`import(/* webpackIgnore: true */'http://localhost:3003').then(module => ... )`).
Also configured webpack to set `mode` to the value of `NODE_ENV` environment variable, so we can run the dev server on `development` mode and the build task on `production` mode.
=> Serve toolkit files directly on development mode when running the dev server

.storybook/main.js, jest.config.js, src/constants/portal-routes.js, src/core/injector/core/injectorFactory.js, src/core/injector/core/injectorFactory.spec.js, src/core/router.js, src/core/router.spec.js, src/index.js, webpack.config.js
This PR adds several things to allow Connect Portal navigation from an extension:
- The injector factory function now returns a new method, `navigateTo`, that can be used to emit events to the Connect Portal to perform navigation.
- The new `connectPortalRoutes` and `connectPortalRoutesDict` constants map several SPA routes
- The new `processRoute` is able to process routes defined in the `connectPortalRoutesDict`
In short, we can perform navigation in several ways:
- Plain string: `navigateTo('/marketplaces/MP-123')`
- Route object: `navigateTo({ name: 'marketplaces.details, params: { id: 'MP-123' } })`
- `connectPortalRoutesDict`: `navigateTo(connectPortalRoutesDict.marketplaceDetails, 'MP-123')`
Having these options allows us to have great level of flexibility, without adding much …
=> LITE-29284: Add Connect Portal navigation functionality

components/src/index.js, components/webpack.config.js, package.json, tools/api/fastApi/adapter.js, tools/api/fastApi/adapter.spec.js, tools/api/fastApi/index.js, tools/api/fastApi/vue-composable.js, tools/api/fastApi/vue-composable.spec.js, tools/webpack.config.js, webpack-dev.config.js, webpack.config.js
- Added conditions to not perform a request is there is no next page or no previous page in the `fastApiTableAdapter` module.
- Fixed tools export in `package.json`, previous config was not correct. Works fine now.
- Split build and dev (serve) Webpack configs in two files to have a clean configuration when building the project.
- Changed tools' Webpack config: Removed `index` export, opting for having two separate files exposed: one for the adapter and one for the composable, so Vue is not required when using the base adapter. Vue is declared as an external dependency, which means it is not bundled with the tools' exports, and it will rely instead on the version of Vue used by the end user.
- Cleaned up main export, exporting everything directly. Way more readable and clear.
---
With …
=> LITE-29547: Control if next & previous actions are allowed in fast API adapter & fix export config for tools

.github/workflows/build.yml, components/src/widgets/complexTable/widget.spec.js, package.json, tools/build/vite/flatten-html-pages-directory.js, tools/build/vite/flatten-html-pages-directory.spec.js, tools/build/vite/index.js, tools/build/vite/index.spec.js, tools/vue/toolkit.js, tools/vue/toolkit.spec.js, tools/webpack.config.js
I create this PR to add some more functionality in the Connect UI Toolkit to make our lives easier when working with Connect extensions.
This PR adds two new features:
- A Vue plugin to use the toolkit app instance in the extensions' Vue components.
- A function to generate a default Vite config to be used in all Connect extensions that use Vite.
---
It is a very straight forward Vue plugin that allows us to have access to the toolkit app instance inside Vue components.
Besides exposing the raw toolkit app instance, it has a reactive property, `sharedContext`, that is updated when the shared context from the Connect SPA to the Extension changes (this is the state we provide with the `value/v-model` to `c-slot` in the SPA).
It can be used in several ways:
Options API:
```js
export default …
```
=> Add helpers for Vue and Vite extensions

.npmignore, package-lock.json, package.json
Publishing process broke when I updated the version for the Github action we use to publish the toolkit to NPM.
For reasons that I don't understand, the previous version of the action ignored the contents of `.gitignore`, which was fixed in newer versions. However, our process relied on that incorrect step. I created the `.npmignore` file to pick which files are published to NPM. This means to ignore everything but files under `/dist` directory (created when running `npm run build`) and `LICENSE`, `README.md` and `package.json` files. I think that it does not make sense to have all the project files available when installing the package, but let me know if you'd prefer it this way.
Also updated the package version to 30.2.1
=> Add .npmignore file to select which files need to be packed when publishing the package

components/src/widgets/complexTable/widget.vue, components/src/widgets/table/widget.vue
Added the option to work with fixed-width columns in tables (like we do in the SPA)
=> Add fixed layout to Table widget

components/src/stories/Menu.stories.js, components/src/widgets/menu/widget.spec.js, components/src/widgets/menu/widget.vue
Alignment needs to be configured to be able to render some menus properly (this screenshot is using the new code):
I only added left & right alignment, we can add others in the future if needed.
=> Add alignment options to Menu component

components/src/stories/Navigation.stories.js, components/src/stories/View.stories.js, components/src/widgets/navigation/widget.vue, components/src/widgets/view/widget.vue
Added the option to show a back button in the Navigation (& View) component:
=> Add option to show a back button to Navigation and View components

components/src/widgets/view/widget.vue
Minor fix to properly display the View component.
Now (👍):
Before (👎):
=> Fix view component's content display

components/src/core/injector/core/Core.js, components/src/core/injector/core/Core.spec.js, components/src/core/injector/core/launcher.js, components/src/core/injector/core/launcher.spec.js, components/src/widgets/view/widget.vue
Several things are sub-par in the current implementation:
- The `$size` event is triggered using an interval
- Size is based on the document element
This PR refactors the way we trigger the `$size` event and how we calculate the size itself:
- Replaces interval-based size update with a `ResizeObserver` instance.
- Uses the body element to measure size, to avoid issues that come with using the document element
Also added `"overflow:scroll"` to the View widget's content holder element, so we have a behaviour more in line with the Connect SPA.
These changes are backwards compatible, since there is no external API to mess with the `$size` event, so no need to update the major version after this is merged.
=> Refactor $size event behavior

components/src/widgets/menu/widget.spec.js, components/src/widgets/menu/widget.vue
- fixed menu closing when multiple menus present
- also add closeOnClickInside prop
https://github.com/cloudblue/connect-ui-toolkit/assets/52078551/57eacb00-8336-478a-94f1-3e1f062d9953
=> LITE-29655 fix menu closing when multiple menus present

components/src/stories/Menu.stories.js, components/src/widgets/menu/widget.spec.js, components/src/widgets/menu/widget.vue
Added the `fullWidth` prop to the Menu widget, to work in cases like this screenshot:
<kbd><img width="500" alt="Screenshot 2024-02-27 at 13 51 54" src="https://github.com/cloudblue/connect-ui-toolkit/assets/50662025/49f91b31-bad0-4f6a-a7c3-8e3d3b50c36c"></kbd>
=> Add "fullWidth" prop to the Menu widget

components/src/stories/TextField.stories.js, components/src/widgets/textfield/widget.spec.js, components/src/widgets/textfield/widget.vue
- Add the `value` prop to set the value from outside the component
- Add `placeholder` prop
- Add `suffix` prop
- Refactor the component to use composition API
- Update the widget's story
Some screenshots:
- Placeholder:
<kbd><img width="400" alt="placeholder" src="https://github.com/cloudblue/connect-ui-toolkit/assets/50662025/482a71f7-e0cf-48a1-8101-6f35e635e2c3"></kbd>
- Suffix:
<kbd><img width="400" alt="suffix" src="https://github.com/cloudblue/connect-ui-toolkit/assets/50662025/c9dd4f44-3961-4e5f-9306-0acd36d4d21f"></kbd>
=> Improve Textfield widget

README.md
Added some cool status badges in the README file. They look like this:
<a href="https://npmjs.com/package/@cloudblueconnect/connect-ui-toolkit"><img src="https://img.shields.io/npm/v/%40cloudblueconnect%2Fconnect-ui-toolkit?logo=npm" alt="NPM package"></a> <a href="https://github.com/cloudblue/connect-ui-toolkit/actions/workflows/build.yml"><img src="https://img.shields.io/github/actions/workflow/status/cloudblue/connect-ui-toolkit/build.yml" alt="CI build"></a> <a href="https://sonarcloud.io/summary/overall?id=connect-ui-toolkit"><img src="https://sonarcloud.io/api/project_badges/measure?project=connect-ui-toolkit&metric=alert_status" alt="Sonar Quality Gate"></a> <a href="https://sonarcloud.io/summary/overall?id=connect-ui-toolkit"><img …
=> Add status badges in README

tools/build/vite/index.js, tools/build/vite/index.spec.js
Refactored `defineExtensionConfig` to be a function (see [Vite - Conditional configuration](https://vitejs.dev/config/#conditional-config)), so it can be aware of Vite's mode (`development`, `production`) in order to set up source maps and minification properly.
This needs to be considered as a breaking change, so the major version of the package will need to be updated. This won't require any change in most cases, since the helper is mostly used directly as the argument to Vite's `defineConfig`method, but if someone is using that differently, it will require some modifications.
The following setup (used on the Connect BI Reporter extension) will work without any changes:
```js
// vite.config.js
import { defineExtensionConfig } from '@cloudblueconnect/connect-ui-toolkit/tools/build/vite'; …
```
=> Make defineExtensionConfig aware of Vite's mode

components/src/index.js, components/src/stories/Select.stories.js, components/src/widgets/select/widget.spec.js, components/src/widgets/select/widget.vue
Ported the simple select component from the Connect BI Reporter extension to the toolkit.
=> LITE-29837: Add simple Select component

.storybook/main.js, components/jest.config.js, components/src/composables/validation.js, components/src/composables/validation.spec.js, components/src/stories/Select.stories.js, components/src/stories/TextField.stories.js, components/src/widgets/menu/widget.vue, components/src/widgets/select/widget.spec.js, components/src/widgets/select/widget.vue, components/src/widgets/textfield/widget.spec.js, components/src/widgets/textfield/widget.vue, components/webpack.config.js, package-lock.json, package.json
This PR adds input validation to `Textfield` and `Select` components, plus other fixes:
- Create `useFieldValidation` composable to validate input fields against rules
- Implement validation in `Textfield` and `Select` components
- Other `Textfield` fixes: fixed focused and label styles, added hint, fixed focus behaviour
- Other `Select` fixes: fixed focused styles, added customisation to option rendering, add `menuProps`
- Emit `"opened"` and `"closed"` when `Menu` widget is toggled
- Add new stories for `Textfield` and `Select`
---
Validation works the same way as in the SPA: `rules` is an array of functions, and validation is only successful if the rule returns explicitly `true`. If the rule fails, it should return an error message string.
Example of a rule:
```js
const isRequired = …
```
=> LITE-29837: Add input validation to Textfield and Select + other fixes

components/src/stories/Select.stories.js, components/src/stories/TextField.stories.js, components/src/widgets/select/widget.vue, components/src/widgets/textfield/widget.vue
The `required` prop adds the classic required asterisk:
=> LITE-30032: Add "required" prop to Select and TextField

components/src/index.js, components/src/stories/Alert.stories.js, components/src/stories/Radio.stories.js, components/src/stories/Textarea.stories.js, components/src/widgets/alert/widget.spec.js, components/src/widgets/alert/widget.vue, components/src/widgets/radio/widget.spec.js, components/src/widgets/radio/widget.vue, components/src/widgets/textarea/widget.spec.js, components/src/widgets/textarea/widget.vue
=> Add textarea, alert and radio button

components/src/stories/Button.mdx, components/src/stories/Button.stories.js, components/src/stories/Menu.stories.js, components/src/widgets/button/widget.spec.js, components/src/widgets/button/widget.vue, components/src/widgets/complexTable/widget.vue, components/src/widgets/icon/widget.vue, components/src/widgets/navigation/widget.vue, components/src/widgets/table/widget.vue, package-lock.json, package.json
You can check the mockups here: https://www.figma.com/file/iWvG1cSD2xzbGS2KAB1DgV/Connect-UI-Guides-%26-Specs?type=design&node-id=1-4009&mode=design&t=5CPLKuHbPQnKMEJh-0
Storybook for the branch: https://63b6ef3ead16487d250fd350-bywagzpucy.chromatic.com/?path=/story/components-button--base
=> LITE-30099: Update button component to match the design

components/src/widgets/select/widget.spec.js, components/src/widgets/select/widget.vue, components/src/widgets/textfield/widget.spec.js, components/src/widgets/textfield/widget.vue
- Remove red asterisk in labels for required fields, use "(Optional)" text instead for non-required fields
=> LITE-30108: Update styles for "required" inputs

components/src/stories/Textarea.stories.js, components/src/widgets/menu/widget.vue, components/src/widgets/textarea/widget.vue, components/src/widgets/textfield/widget.vue
- Add "focused" class to textarea and textfield if navigation is done with keyboard
- Fix space between menu's content and container
- Set textarea's default font family to inherit, add "monospace" prop
- Fix textarea's label "for" attribute
- Add new story to textarea to showcase validation
=> LITE-30423: Minor ui fixes

components/src/index.js, components/src/stories/Autocomplete.stories.js, components/src/widgets/autocomplete/widget.spec.js, components/src/widgets/autocomplete/widget.vue, components/src/widgets/select/widget.spec.js, components/src/widgets/select/widget.vue, components/src/widgets/textfield/widget.vue
- Create Autocomplete component
- Small style alignments in Select component after review with Max T.
**UI reviewed with Max T.**
=> Create autocomplete component

tools/vite.config.js
Exports under tools build were not working after the package was updated to be an ES module
=> Fix tools build as an ES module

components/src/stories/Card.stories.js, components/src/widgets/card/widget.vue, components/src/widgets/menu/widget.spec.js, components/src/widgets/menu/widget.vue, components/src/widgets/select/widget.spec.js, components/src/widgets/select/widget.vue, components/src/widgets/textarea/widget.vue, components/src/widgets/textfield/widget.spec.js, components/src/widgets/textfield/widget.vue, package.json
- Update `Card` widget styles to match the specification
- Add `disabled` state to `Menu`, `Select`, `Textarea` and `Textfield` widgets
Also added a "precommit" script, to run tests, lint, format and build sequentially
=> LITE-31805: Fix important QoL issues in Card and inputs
